image: golang:latest

variables:
  ADMIN_AUTHENTICATION_TOKEN: unittest-api-key
  MIGRATE_DATABASE: "True"
  http_proxy: http://172.17.0.1:3128
  https_proxy: http://172.17.0.1:3128
  HTTP_PROXY: http://172.17.0.1:3128
  HTTPS_PROXY: http://172.17.0.1:3128

stages:
  - test
  - build
  - deploy

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)

test:
  stage: test
  services:
    - name: ghcr.io/matthewjohn/terrareg:latest
      alias: terrareg
      
  variables:
    TF_ACC: "1"
    TERRAREG_URL: "http://terrareg:5000"
    TERRAREG_API_KEY: unittest-api-key
  script:
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - go build
  artifacts:
    paths:
      - terraform-provider-terrareg

release:
  stage: deploy
  image: semantic-release:latest
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
    GIT_STRATEGY: clone
  script:
    - semantic-release
  only:
    - main
