image: golang:latest

variables:
  ADMIN_AUTHENTICATION_TOKEN: unittest-api-key
  MIGRATE_DATABASE: "True"

stages:
  - test
  - build

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)

test:
  stage: test
  services:
    - name: ghcr.io/matthewjohn/terrareg:latest
      alias: terrareg
      
  variables:
    TF_ACC: "1"
    TERRAREG_URL: "http://terrareg:5000"
    TERRAREG_API_KEY: ${ADMIN_AUTHENTICATION_TOKEN}
  script:
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - go build
  artifacts:
    paths:
      - terraform-provider-terrareg
