image: golang:latest

variables:
  ADMIN_AUTHENTICATION_TOKEN: unittest-api-key
  MIGRATE_DATABASE: "True"
  http_proxy: http://172.17.0.1:3128
  https_proxy: http://172.17.0.1:3128
  HTTP_PROXY: http://172.17.0.1:3128
  HTTPS_PROXY: http://172.17.0.1:3128

stages:
  - test
  - build
  - deploy

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)

test:
  stage: test
  services:
    - name: ghcr.io/matthewjohn/terrareg:latest
      alias: terrareg
      
  variables:
    TF_ACC: "1"
    TERRAREG_URL: "http://terrareg:5000"
    TERRAREG_API_KEY: unittest-api-key
    GIT_PROVIDER_CONFIG: '[{"name": "Github", "base_url": "https://github.com/{namespace}/{module}", "clone_url": "ssh://git@github.com:{namespace}/{module}.git", "browse_url": "https://github.com/{namespace}/{module}/tree/{tag}/{path}"}, {"name": "Bitbucket", "base_url": "https://bitbucket.org/{namespace}/{module}", "clone_url": "ssh://git@bitbucket.org:{namespace}/{module}-{provider}.git", "browse_url": "https://bitbucket.org/{namespace}/{module}-{provider}/src/{tag_uri_encoded}/{path}"}, {"name": "Gitlab", "base_url": "https://gitlab.com/{namespace}/{module}", "clone_url": "ssh://git@gitlab.com:{namespace}/{module}-{provider}.git", "browse_url": "https://gitlab.com/{namespace}/{module}-{provider}/-/tree/{tag}/{path}"}]'
  script:
    - unset http_proxy
    - unset https_proxy
    - unset HTTP_PROXY
    - unset HTTPS_PROXY
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - go build
  artifacts:
    paths:
      - terraform-provider-terrareg

release:
  stage: deploy
  image: semantic-release:latest
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
    GIT_STRATEGY: clone
  script:
    - semantic-release
  only:
    - main
